services:
  - type: web
    name: contestacao-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn -w 1 -t 300 src.main:app
    envVars:
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
