services:
  - type: web
    name: contestacao-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    envVars:
      - key: PORT
        value: 5000
