services:
  - type: web
    name: contestacao-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn src.main:app --timeout 600 --workers 1 --worker-class sync
    envVars:
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
