services:
  - type: web
    name: contestacao-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT -t 180 src.main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
