services:
  - type: web
    name: contestacao-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn src.main:app --timeout 180 --workers 1
    envVars:
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
